apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tetragon
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://helm.cilium.io/
    chart: tetragon
    targetRevision: 1.7.0 
    helm:
      values: |
        tetragon:
          cri:
            enabled: true
            socketHostPath: "/run/k3s/containerd/containerd.sock"
          
          enableProcessCred: true
          enableProcessNs: true
          
          prometheus:
            enabled: true
            serviceMonitor:
              enabled: true
              
        export:
          mode: "stdout"
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true