apiVersion: argoproj.io/v1alpha1
kind: ExternalSecret
metadata:
  name: temporal-db-credentials
  namespace: ecommerce
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: temporal-db-secret
  data:
  - secretKey: password
    remoteRef:
      key: secret/temporal
      property: temporal_pass