---
#ansible-vault <decrypt/encrypt> secrets.yml
- hosts: worker
  become: true
  vars:
    admin_user: "{{ ansible_user | default('ubuntu') }}"
  
  vars_files:
    - files/secrets.yml

  tasks:
    - name: 01. Install updates for Ubuntu
      tags: always
      ansible.builtin.apt:
        upgrade: dist
        update_cache: yes
        autoremove: yes

    - name: 02. Disable UFW Firewall
      ansible.builtin.systemd:
        name: ufw
        state: stopped
        enabled: false
      
    - name: 03. Disable swap
      ansible.builtin.command: swapoff -a
      when: ansible_swaptotal_mb > 0

    - name: 04. Disable swap permanently
      ansible.builtin.replace:
        path: /etc/fstab
        regexp: '^([^#\n]*?\sswap\s+.*)$'
        replace: '# \1'
    
    - name: 05. Install WireGuard + Longhorn packages
      ansible.builtin.apt:
        name:
          - wireguard # for Cilium
          - wireguard-tools # for Cilium
          - open-iscsi # for Longhorn
          - nfs-common # for Longhorn
        state: present
    
    - name: 06. Load kernel modules on boot
      ansible.builtin.copy:
        dest: /etc/modules-load.d/k8s.conf
        content: |
          overlay
          br_netfilter
        mode: '0644'

    - name: 07. Load kernel modules immediately
      ansible.builtin.command: modprobe {{ item }}
      loop:
        - overlay
        - br_netfilter
      changed_when: false

    - name: 08. Create rke2 directory
      ansible.builtin.file:
        path: /etc/rancher/rke2
        state: directory
        mode: '0755'

    - name: 09. Write RKE2 worker configuration
      ansible.builtin.copy:
        dest: /etc/rancher/rke2/config.yaml
        content: |
          server: https://{{ master_ip }}:9345
          token: {{ node_token }}
        mode: '0600'

    - name: 10. Download and execute rke2 agent
      ansible.builtin.shell: |
        curl -sfL https://get.rke2.io | INSTALL_RKE2_TYPE="agent" sh -
      args:
        creates: /usr/local/bin/rke2

    - name: 11. Enable and start rke2-agent
      ansible.builtin.systemd:
        name: rke2-agent
        state: started
        enabled: true

    - name: 12. Disable Root SSH Login
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PermitRootLogin'
        line: 'PermitRootLogin no'
      notify: Restart SSH

  handlers:
    - name: Restart SSH
      ansible.builtin.service:
        name: ssh
        state: restarted