---
- hosts: master
  tasks:
    - name: 01. Install Local Path Provisioner
      kubernetes.core.k8s:
        state: present
        src: https://raw.githubusercontent.com/rancher/local-path-provisioner/v0.0.36/deploy/local-path-storage.yaml

    - name: 02. Make local-path the default StorageClass
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: storage.k8s.io/v1
          kind: StorageClass
          metadata:
            name: local-path
            annotations:
              storageclass.kubernetes.io/is-default-class: "true"

    - name: 03. Install gateway-api
      kubernetes.core.k8s:
        state: present
        src: https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.6.0/standard-install.yaml

    - name: 04. Add Cilium Helm repo
      kubernetes.core.helm_repository:
        name: cilium
        repo_url: https://helm.cilium.io/

    - name: 05. Install Cilium via Helm
      kubernetes.core.helm:
        name: cilium
        chart_ref: cilium/cilium
        release_namespace: kube-system
        state: present
        wait: true
        timeout: 10m0s 
        values:
          kubeProxyReplacement: "true"
          k8sServiceHost: "127.0.0.1"
          k8sServicePort: 6443
          gatewayAPI:
            enabled: true
          encryption:
            enabled: true
            type: wireguard
          l7Proxy: true
          envoy:
            enabled: true
          l2announcements:
            enabled: true
          externalIPs:
            enabled: true
          hubble:
            relay:
              enabled: true
            ui:
              enabled: true