---
- hosts: master
  become: false
  tasks:

    - name: 01. Create Argo CD namespace
      kubernetes.core.k8s:
        name: argocd
        api_version: v1
        kind: Namespace
        state: present

    - name: 02. Add Argo Helm repository
      kubernetes.core.helm_repository:
        name: argo
        repo_url: https://argoproj.github.io/argo-helm

    - name: 03. Install Argo CD via Helm
      kubernetes.core.helm:
        name: argocd
        chart_ref: argo/argo-cd
        release_namespace: argocd
        state: present
        wait: true

    - name: 04. Retrieve Argo CD initial admin password
      kubernetes.core.k8s_info:
        kind: Secret
        name: argocd-initial-admin-secret
        namespace: argocd
      register: argocd_secret

    - name: 05. Print Argo CD password
      ansible.builtin.debug:
        msg: "Argo CD Password: {{ argocd_secret.resources[0].data.password | b64decode }}"

    - name: 06. Port-forward ArgoCd
      ansible.builtin.shell: /var/lib/rancher/rke2/bin/kubectl port-forward svc/argocd-server -n argocd 8080:443 --address 0.0.0.0