---
- hosts: master
  become: true
  vars_files:
    - files/cluster-keys.json
    - files/secrets.yml
  
  vars:
    kubectl_cmd: "/var/lib/rancher/rke2/bin/kubectl --kubeconfig /etc/rancher/rke2/rke2.yaml"

  tasks: 
    - name: 01. Extract Garage Node ID
      ansible.builtin.shell: |
        {{ kubectl_cmd }} exec -n garage garage-0 -- ./garage status | grep -E '^[0-9a-f]{16}' | head -n 1 | awk '{print $1}'
      register: garage_node_id
      changed_when: false

    - name: 02. Assign storage capacity to the Node
      ansible.builtin.command: >
        {{ kubectl_cmd }} exec -n garage garage-0 -- ./garage layout assign {{ garage_node_id.stdout }} --zone dc1 --capacity 20G
      register: layout_assign
      changed_when: "'Assigning' in layout_assign.stdout"
      ignore_errors: true

    - name: 03. Apply the storage layout
      ansible.builtin.command: "{{ kubectl_cmd }} exec -n garage garage-0 -- ./garage layout apply --version 1"
      register: layout_apply
      changed_when: "'Applied' in layout_apply.stdout"
      until: layout_apply.rc == 0
      retries: 5
      delay: 5

    - name: 04. Create S3 Buckets for the Grafana Stack
      ansible.builtin.command: "{{ kubectl_cmd }} exec -n garage garage-0 -- ./garage bucket create {{ item }}"
      loop:
        - loki-logs
        - mimir-blocks
        - tempo-traces
      register: bucket_creation
      changed_when: "'created' in bucket_creation.stdout | lower"
      ignore_errors: true

    - name: 05. Generate S3 API Keys
      ansible.builtin.command: "{{ kubectl_cmd }} exec -n garage garage-0 -- ./garage key create {{ item }}-key"
      loop:
        - loki
        - mimir
        - tempo
      register: api_keys
      changed_when: "'Secret key' in api_keys.stdout"
      ignore_errors: true

    - name: 06. Grant API Keys access to their respective buckets
      ansible.builtin.command: >
        {{ kubectl_cmd }} exec -n garage garage-0 -- ./garage bucket allow {{ item.bucket }} --read --write --owner --key {{ item.key }}-key
      loop:
        - { bucket: 'loki-logs', key: 'loki' }
        - { bucket: 'mimir-blocks', key: 'mimir' }
        - { bucket: 'tempo-traces', key: 'tempo' }
      changed_when: false
      ignore_errors: true

    - name: 07. Save Keys directly to Vault
      ansible.builtin.shell: |
        ACCESS_KEY=$(echo "$GARAGE_STDOUT" | awk -F'Key ID: ' '{print $2}' | tr -d '\r' | awk '{print $1}')
        SECRET_KEY=$(echo "$GARAGE_STDOUT" | awk -F'Secret key: ' '{print $2}' | tr -d '\r' | awk '{print $1}')
        
        {{ kubectl_cmd }} exec -n vault vault-0 -- sh -c "export VAULT_TOKEN='$VAULT_TOKEN'; vault kv put secret/{{ item.item }} access-key=\"$ACCESS_KEY\" secret-key=\"$SECRET_KEY\""
      environment:
        GARAGE_STDOUT: "{{ item.stdout | default('') }}"
        VAULT_TOKEN: "{{ root_token }}" 
      loop: "{{ api_keys.results }}"
      when: item.stdout is defined and 'Secret key' in item.stdout
      no_log: true