---
- hosts: master
  tasks:
    - name: 01. Bootstrap the Cluster (Apply ApplicationSet)
      kubernetes.core.k8s:
        state: present
        src: "https://raw.githubusercontent.com/GiannisStathoudakis/piggymetrics-lab/master/Bootstrap/root.yaml?v=3"