---
- hosts: master
  vars_files:
    - files/cluster-keys.json
  tasks:
    - name: Unlock Vault
      kubernetes.core.k8s_exec:
        namespace: vault
        pod: vault-0
        command: "vault operator unseal {{ item }}"
      loop:
        - "{{ (lookup('file', 'files/cluster-keys.json') | from_json).unseal_keys_b64[0] }}"
        - "{{ (lookup('file', 'files/cluster-keys.json') | from_json).unseal_keys_b64[1] }}"
        - "{{ (lookup('file', 'files/cluster-keys.json') | from_json).unseal_keys_b64[2] }}"