apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tempo
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  source:
    repoURL: https://grafana-community.github.io/helm-charts
    chart: tempo
    targetRevision: 2.2.3
    helm:
      values: |
        tempo:
          extraEnvFrom:
            - secretRef:
                name: tempo-s3-credentials
          
          storage:
            trace:
              backend: s3
              s3:
                bucket: tempo-traces
                endpoint: garage.garage.svc.cluster.local:3900
                insecure: true
                forcepathstyle: true
                
          
  destination:
    server: https://kubernetes.default.svc
    namespace: tempo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true